from .auto_chroma_bg_v3 import (
    NODE_CLASS_MAPPINGS as V3_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as V3_DISPLAY_MAPPINGS,
)
from .auto_chroma_smart import (
    NODE_CLASS_MAPPINGS as SMART_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SMART_DISPLAY_MAPPINGS,
)
from .flower_domain_color import (
    NODE_CLASS_MAPPINGS as FLOWER_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as FLOWER_DISPLAY_MAPPINGS,
)
from .hsl_color_adjust import (
    NODE_CLASS_MAPPINGS as HSL_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as HSL_DISPLAY_MAPPINGS,
)

# 合并所有节点
NODE_CLASS_MAPPINGS = {**V3_MAPPINGS, **SMART_MAPPINGS, **FLOWER_MAPPINGS, **HSL_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**V3_DISPLAY_MAPPINGS, **SMART_DISPLAY_MAPPINGS, **FLOWER_DISPLAY_MAPPINGS, **HSL_DISPLAY_MAPPINGS}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
